In [2]:
import pandas as pd

In [3]:
# Load Data

data = pd.read_csv("../raw_data/statewise_crime_data.csv")

In [4]:
# Remove the Serial Number

data = data.drop(columns = ["Sl. No."])

In [14]:
# Rename the columns name

data.columns = ["State_UT" , "Crime_2020" , "Crime_2021" , "Crime_2022" , "Mid-Year_Projected_Population(2022)" , "IPC_2022" , "Chargesheeting_Rate(2022)"]

In [17]:
# Remove the Total rows

data_clean = data[~data["State_UT"].str.contains("Total" , case=False)]

data_clean.tail()

,State_UT,Crime_2020,Crime_2021,Crime_2022,Mid-Year_Projected_Population(2022),IPC_2022,Chargesheeting_Rate(2022)
32,Delhi,249192,291904,300429,211.0,1424.1,30.2
33,Jammu and Kashmir,25233,27447,25915,135.4,191.4,77.1
34,Ladakh,387,519,439,3.0,146.8,82.4
35,Lakshadweep,107,89,64,0.7,92.8,73.5
36,Puducherry,6725,3851,3237,16.2,199.7,91.3

In [19]:
# Top 10 State or UT in Crimes (2022)

top_crimes = data_clean.sort_values(by="Crime_2022" , ascending=False).head(10)
top_crimes[["State_UT" , "Crime_2022"]]

          State_UT  Crime_2022
25   Uttar Pradesh      401787
13     Maharashtra      374038
32           Delhi      300429
12  Madhya Pradesh      298578
20       Rajasthan      236090
11          Kerala      235858
3            Bihar      211079
22      Tamil Nadu      193913
0   Andhra Pradesh      158547
27     West Bengal      156503

In [20]:
# Top 5 State or UT in Crime Rate (2022)

top_crime_rate = data_clean.sort_values(by="IPC_2022" , ascending=False).head(5)
top_crime_rate[["State_UT" , "IPC_2022"]]

          State_UT  IPC_2022
32           Delhi    1424.1
11          Kerala     661.0
7          Haryana     418.6
23       Telangana     400.1
12  Madhya Pradesh     347.6

In [22]:
# state and UT's with low crime rate

low_crime_rate = data_clean.sort_values(by="IPC_2022").head(5)
low_crime_rate[["State_UT" , "IPC_2022"]]

       State_UT  IPC_2022
17     Nagaland      45.4
21       Sikkim      80.3
15    Meghalaya      87.6
24      Tripura      88.7
35  Lakshadweep      92.8

In [24]:
# Best Performing States on basis of Chargesheeting Rate

good_chargesheeting_rate = data_clean.sort_values(by="Chargesheeting_Rate(2022)").head(5)
good_chargesheeting_rate[["State_UT" , "Chargesheeting_Rate(2022)"]]

     State_UT  Chargesheeting_Rate(2022)
14    Manipur                       10.4
15  Meghalaya                       26.9
32      Delhi                       30.2
2       Assam                       32.6
7     Haryana                       43.3

In [11]:
# Worst Performing States on basis of Chargesheeting Rate

worst_chargesheeting_rate = data_clean.sort_values(by="Chargesheeting_Rate(2022)").tail(5)
worst_chargesheeting_rate[["State_UT" , "Chargesheeting_Rate(2022)"]]

          State_UT  Chargesheeting_Rate(2022)
12  Madhya Pradesh                       86.6
6          Gujarat                       89.8
27     West Bengal                       90.6
36      Puducherry                       91.3
11          Kerala                       96.0

In [26]:
# Crime Increase / Decrease Percentage (2020 -> 2022)

data_clean = data_clean.copy()
data_clean.loc[: , "Crime_change(%)"] = (data_clean["Crime_2022"] - data_clean["Crime_2020"]) / data_clean["Crime_2022"] * 100
data_clean[["State_UT" , "Crime_2020" , "Crime_2022" , "Crime_change(%)"]]

data_clean["Crime_change(%)"] = data_clean["Crime_change(%)"].round(2)
data_clean["Crime_change(%)"] = data_clean["Crime_change(%)"].astype(int).astype(str) + "%"

In [35]:
crime_percentage = data_clean[["State_UT" , "Crime_2020" , "Crime_2022" , "Crime_change(%)"]]
crime_percentage

,State_UT,Crime_2020,Crime_2022,Crime_change(%)
0,Andhra Pradesh,188997,158547,-19%
1,Arunachal Pradesh,2244,2308,2%
2,Assam,111558,59315,-88%
3,Bihar,194698,211079,7%
4,Chhattisgarh,65216,73822,11%
5,Goa,3393,2711,-25%
6,Gujarat,381849,134600,-183%
7,Haryana,103276,125435,17%
8,Himachal Pradesh,14803,13231,-11%
9,Jharkhand,51033,48726,-4%
10,Karnataka,106350,129461,17%
11,Kerala,149099,235858,36%
12,Madhya Pradesh,283881,298578,4%
13,Maharashtra,394017,374038,-5%
14,Manipur,2349,3029,22%
15,Meghalaya,2871,2914,1%
16,Mizoram,1787,3587,50%
17,Nagaland,1022,1008,-1%
18,Odisha,108533,143414,24%
19,Punjab,49870,43738,-14%
20,Rajasthan,193279,236090,18%
21,Sikkim,504,549,8%
22,Tamil Nadu,891700,193913,-359%
23,Telangana,135885,151849,10%
24,Tripura,4010,3653,-9%
25,Uttar Pradesh,355110,401787,11%
26,Uttarakhand,13812,16967,18%
27,West Bengal,158060,156503,0%
29,Andaman and Nicobar Islands,482,460,-4%
30,Chandigarh,2583,2941,12%
31,Dadra and Nagar Haveli and Daman and Diu,441,1184,62%
32,Delhi,249192,300429,17%
33,Jammu and Kashmir,25233,25915,2%
34,Ladakh,387,439,11%
35,Lakshadweep,107,64,-67%
36,Puducherry,6725,3237,-107%

In [38]:
# Export Cleaned Data (CSV)

data_clean.to_csv("../processed_data/Cleaned_data.csv")
top_crimes.to_csv("../processed_data/top_crimes_states&UT.csv")
top_crime_rate.to_csv("../processed_data/top_crime_rate.csv")
low_crime_rate.to_csv("../processed_data/low_crime_rate.csv")
good_chargesheeting_rate.to_csv("../processed_data/good_chargesheeting_rate.csv")
worst_chargesheeting_rate.to_csv("../processed_data/worst_chargesheeting_rate.csv")
crime_percentage.to_csv("../processed_data/crime_percentage(2020-2022).csv")

# Export in Excel
with pd.ExcelWriter("../processed_data/Crime_Analysis_Report.xlsx") as writer:
    
    # Sheet 1: The full cleaned dataset
    data_clean.to_excel(writer, sheet_name='Full_Cleaned_Data')
    
    # Sheet 2: Top 10 State or UT in Crimes (2022)
    top_crimes.to_excel(writer, sheet_name='Top_10_Volume')
    
    # Sheet 3: Top 5 State or UT in Crime Rate (2022)
    top_crime_rate.to_excel(writer, sheet_name='Top_5_Crime_Rate')

    # Sheet 4: state and UT's with low crime rate
    low_crime_rate.to_excel(writer, sheet_name='Top_5_Crime_Rate')
    
    # Sheet 4: Chargesheeting Performance (Best & Worst)
    good_chargesheeting_rate.to_excel(writer, sheet_name='Police_Performance')
    worst_chargesheeting_rate.to_excel(writer, sheet_name='Police_Performance')